version: '3'

services:
  django_app:
    build: .
    container_name: django_app
    networks:
      - jenkins_network
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - .:/app

networks:
  jenkins_network:
    external: true
