version: '3.8'

services:
  django_app:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /app:/app
    networks:
      - cicd_test_jenkins-network
networks:
  cicd_test_jenkins-network:
    external: true
